# Generated by Django 6.1.1 on 2026-09-16 01:35

import django.db.models.deletion
import orders.models.order
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, default=orders.models.order.generate_order_number, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('PREPARING', 'Preparing / Roasting'), ('EN_ROUTE', 'Customer En Route'), ('ARRIVED_CURBSIDE', 'Arrived Curbside'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=30)),
                ('fulfillment_type', models.CharField(choices=[('COUNTER_PICKUP', 'Counter Pickup'), ('CURBSIDE', 'Curbside Pickup')], default='COUNTER_PICKUP', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('curbside_spot', models.CharField(blank=True, help_text='e.g. Spot 3 or Silver Subaru', max_length=50)),
                ('total_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customization_notes', models.TextField(blank=True, help_text='e.g. Extra hot, oat milk, grind size details')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
