# Generated by Django 6.1.1 on 2026-09-16 02:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_tendered_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change_due_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='tender_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('EXTERNAL_CARD', 'Card Terminal'), ('WEBLN', 'WebLN / Lightning')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='terminal_id',
            field=models.CharField(blank=True, default='REG-01', max_length=32),
        ),
    ]
