[project]
name = "greenbean-dotapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dcbyers13", email = "dcbyers13@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
greenbean-dotapp = "greenbean_dotapp:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
