[project]
name = "greenbean-dotapp"
version = "0.1.0"
description = "Green Bean Coffee Collective — Core Web Engine"
readme = "README.md"
authors = [
    { name = "dcbyers13", email = "dcbyers13@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-environ>=0.12.0",
    "gunicorn>=23.0.0",
    "whitenoise>=6.8.0",
]

[tool.uv]
package = false
