# Generated by Django 6.1.1 on 2026-09-16 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_revenue_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operating_costs_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reinvestment_reserve_usd', models.DecimalField(decimal_places=2, help_text='Retained capital for equipment/growth', max_digits=12)),
                ('distributable_surplus_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('worker_pool_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('community_pool_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('DISBURSED', 'Disbursed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Surplus Distribution',
                'verbose_name_plural': 'Surplus Distributions',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='WorkerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('did', models.CharField(help_text='Decentralized Identifier or pubkey', max_length=100, unique=True)),
                ('role', models.CharField(default='Worker-Owner', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Worker Member',
                'verbose_name_plural': 'Worker Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('station', models.CharField(choices=[('BARISTA', 'Barista'), ('ROASTER', 'Roaster'), ('BAKERY', 'Bakery'), ('MAINTENANCE', 'Maintenance'), ('ADMIN', 'Administration')], max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_logs', to='iyou_poly.workermember')),
            ],
            options={
                'verbose_name': 'Labor Log',
                'verbose_name_plural': 'Labor Logs',
                'ordering': ['-shift_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerDividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividend_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_dividends', to='iyou_poly.surplusdistribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='iyou_poly.workermember')),
            ],
            options={
                'ordering': ['-dividend_usd', 'member__name'],
                'unique_together': {('distribution', 'member')},
            },
        ),
    ]
