# Generated by Django 6.1.1 on 2026-09-16 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenCoffeeLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_country', models.CharField(max_length=100)),
                ('region_farm', models.CharField(max_length=200)),
                ('producer_coop', models.CharField(max_length=200)),
                ('varietal', models.CharField(default='Typica / Bourbon', max_length=100)),
                ('process_method', models.CharField(choices=[('WASHED', 'Washed'), ('NATURAL', 'Natural'), ('HONEY', 'Honey'), ('ANAEROBIC', 'Anaerobic')], default='WASHED', max_length=50)),
                ('altitude_meters', models.DecimalField(decimal_places=1, default=1600.0, max_digits=6)),
                ('harvest_date', models.DateField()),
                ('green_stock_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fair_price_paid_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Green Coffee Lot',
                'verbose_name_plural': 'Green Coffee Lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoastProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roast_name', models.CharField(max_length=100)),
                ('roast_level', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM_LIGHT', 'Medium-Light'), ('MEDIUM', 'Medium'), ('MEDIUM_DARK', 'Medium-Dark'), ('DARK', 'Dark')], default='MEDIUM', max_length=20)),
                ('tasting_notes', models.CharField(help_text='e.g. Citrus, Jasmine, Milk Chocolate', max_length=255)),
                ('target_drop_temp_f', models.PositiveIntegerField(default=415)),
                ('development_time_sec', models.PositiveIntegerField(default=120)),
            ],
            options={
                'verbose_name': 'Roast Profile',
                'verbose_name_plural': 'Roast Profiles',
                'ordering': ['roast_name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_single_origin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.greencoffeelot')),
                ('roast_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.roastprofile')),
            ],
            options={
                'verbose_name': 'Coffee Product',
                'verbose_name_plural': 'Coffee Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('form_factor', models.CharField(choices=[('WHOLE_BEAN', 'Whole Bean'), ('GROUND', 'Ground Retail'), ('RAW_GREEN', 'Raw Green Coffee'), ('LIVE_CUP', 'Live Cup / Espresso Bar'), ('AIRPOT', 'Airpot / Bulk Brew'), ('CONFECTION', 'Confection / Sweet')], default='WHOLE_BEAN', max_length=30)),
                ('package_weight_oz', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 12.0 for 12oz retail bag, 32.0 for 2lb', max_digits=6, null=True)),
                ('grind_option', models.CharField(choices=[('WHOLE_BEAN', 'Whole Bean (Unopened)'), ('COARSE', 'Coarse (French Press / Cold Brew)'), ('MEDIUM', 'Medium (Drip / Auto-Drip)'), ('CHEMEX', 'Medium-Fine (Chemex / Pour Over)'), ('FINE', 'Fine (Espresso / Moka)'), ('TURKISH', 'Extra Fine (Turkish)')], default='WHOLE_BEAN', max_length=30)),
                ('retail_price_usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_units', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.coffeeproduct')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'retail_price_usd'],
            },
        ),
        migrations.CreateModel(
            name='RoastBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('green_weight_used_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roasted_yield_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roasted_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_batches', to='catalog.greencoffeelot')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.roastprofile')),
            ],
            options={
                'verbose_name': 'Roast Batch',
                'verbose_name_plural': 'Roast Batches',
                'ordering': ['-roasted_at'],
            },
        ),
    ]
