# Generated by Django 6.1.1 on 2026-09-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproduct',
            name='brand_line',
            field=models.CharField(blank=True, default='Green Bean Coffee Collective', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='form_factor',
            field=models.CharField(choices=[('WHOLE_BEAN', 'Whole Bean'), ('GROUND', 'Ground Coffee'), ('RAW_GREEN', 'Raw Green Coffee'), ('LIVE_CUP', 'Live Drip / Pour'), ('SPECIALTY_BEVERAGE', 'Specialty Espresso / Craft Drink'), ('AIRPOT', 'Meeting Airpot'), ('BAKERY', "Violette's Bakery"), ('CONFECTION', 'Artisanal Confection')], default='WHOLE_BEAN', max_length=30),
        ),
    ]
