# Generated by Django 6.1.1 on 2026-09-16 01:35

import django.db.models.deletion
import telemetry.models.beacon
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalBeacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ephemeral_token', models.CharField(db_index=True, default=telemetry.models.beacon.generate_beacon_token, max_length=64, unique=True)),
                ('arrival_status', models.CharField(choices=[('PENDING', 'Pending Customer Movement'), ('EN_ROUTE', 'Customer En Route'), ('ARRIVED', 'Customer Arrived at Curbside')], default='PENDING', max_length=20)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=telemetry.models.beacon.default_beacon_expiry)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_beacon', to='orders.order')),
            ],
            options={
                'verbose_name': 'Arrival Beacon',
                'verbose_name_plural': 'Arrival Beacons',
                'ordering': ['-expires_at'],
            },
        ),
    ]
